{% set name = "pytest-httpx" %}
{% set version = "0.34.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3ca4b0975c0f93b985f17df19e76430c1086b5b0cce32b1af082d8901296a735

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - httpx ==0.27.*
    - pytest >=7.*,<9
    - python >=3.9

test:
  imports:
    - pytest_httpx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colin-b.github.io/pytest_httpx/
  summary: Send responses to httpx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
    - dgasmith
