{% set name = "pytest-httpx" %}
{% set version = "0.29.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_httpx-{{ version }}.tar.gz
  sha256: ed08ed802e2b315b83cdd16f0b26cbb2b836c29e0fde5c18bc3105f1073e0332

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - httpx ==0.25.*
    - pytest >=6.*,<8
    - python >=3.9

test:
  imports:
    - pytest_httpx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://colin-b.github.io/pytest_httpx/
  summary: Send responses to httpx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
    - dgasmith
