{% set name = "pytest-httpx" %}
{% set version = "0.35.0" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d619ad5d2e67734abfbb224c3d9025d64795d4b8711116b1a13f72a251ae511f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - httpx ==0.28.*
    - pytest >=7.*,<9
    - python >={{ python_min }}

test:
  imports:
    - pytest_httpx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://colin-b.github.io/pytest_httpx/
  summary: Send responses to httpx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - owenlamont
    - dgasmith
